### ISSUE TITLE
Offer to (co)maintain this gem

### ISSUE THREAD

**Issue by dblock** [fetch/faraday_hal_middleware#3]
Hi @jaap & @koenpunt.

I'm coming via https://github.com/codegram/hyperclient/issues/129, am co-maintainer of Hyperclient, https://github.com/ruby-grape/grape, https://github.com/intridea/hashie and more.

Can I/we please help with faraday_hal_middleware? We'd like to get some PRs merged (#1 and #2) and generally move this forward. I'll happily take over maintenance and maybe @espen would like to join too.

I'm dblock[at]dblock[dot]org for Rubygems.

**Comment by espen** [comment]
I'm not that familiar with faraday but can assist with responding to and fixing basic issues like the ones I reported and made pull requests for.

**Comment by koenpunt** [comment]
Hi @dblock, thanks for your interest. I've just merged and released the 2 pending pull requests. But since I'm not actively using this gem I'm fine with adding you as a contributor (which I just did).

**Comment by dblock** [comment]
Amazing, thanks @koenpunt. Care to add me to Rubygems too and you don't have to worry about this one for a while at least anymore?

**Comment by koenpunt** [comment]
So eager you are ;) Just added you there too!

**Comment by dblock** [comment]
I am just trying to reduce bus factor :) Can we add @espen too? He has been helping with hyperclient quite a bit.

**Comment by dblock** [comment]
Last question: do you care to PR/merge changes or can we just run with this?

**Comment by koenpunt** [comment]
@espen is added too.

> Last question: do you care to PR/merge changes or can we just run with this?

What do you mean? As in still wanting to have a voice in new PRs? Not really. Also I doubt that the API surface will change anytime soon, so I don't expect any major changes anyway. But I'll probably have a look at anything that comes by, so if I feel the need you'll hear from me.

All I can say, good luck with it :)

**Comment by dblock** [comment]
Right on. We'll keep this alive since it has been a dependency for a very popular hyperclient. Thanks for making the gem and say hi if you're in NY I'll buy you a drink or ten.

**Comment by koenpunt** [comment]
Cool, when I'll cross the pond someday again!

>  it has been a dependency for a very popular hyperclient

Now I remember; I actually created this Gem for use with Hyperclient 🙃(https://github.com/codegram/hyperclient/commit/9e81da54e896d603c42f9bef3eb2cb0ebe01a460)

**Comment by dblock** [comment]
Haha awesome. One last piece of help in enabling travis pls, https://github.com/fetch/faraday_hal_middleware/pull/4
