### ISSUE TITLE
faraday_middleware is deprecated 

### ISSUE THREAD

**Issue by espen** [fetch/faraday_hal_middleware#8]
From https://github.com/lostisland/faraday_middleware
> As highlighted in Faraday's UPGRADING guide, faraday_middleware is DEPRECATED, and will not be updated to support Faraday 2.0. If you rely on faraday_middleware in your project and would like to support Faraday 2.0:
> 
> The json middleware (request and response) are now both bundled with Faraday 🙌
> The instrumentation middleware is bundled with Faraday
> All other middleware, they'll be re-released as independent gems compatible with both Faraday v1 and v2
> Most of the middleare are looking for adoption, contributors that would like to maintain them. If you'd like to maintain any middleware, have any question or need any help, we're here! Please reach out opening an issue or a discussion.

More info on https://github.com/lostisland/faraday/blob/main/UPGRADING.md#faraday-middleware-deprecation

**Comment by dblock** [comment]
Implemented support for Faraday 2.x in https://github.com/fetch/faraday_hal_middleware/pull/9.
